<a href="https://colab.research.google.com/github/Shubham5787/practice-project/blob/main/practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [1,2,3,4,5,6]

In [ ]:
a.append ({1:10})

In [ ]:
a

[1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 'a', 10.5, True, [1, 2, 3], (1, 2, 3), {1: 10}]

In [ ]:
print ('updated_a:',a)

updated_a: [1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 'a', 10.5, True, [1, 2, 3], (1, 2, 3), {1: 10}]


In [ ]:
print (a[4])

5


In [ ]:
print(a)

[1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 'a', 10.5, True, [1, 2, 3], (1, 2, 3), {1: 10}]


In [ ]:
b = [1,2,3,4,6,7]

In [ ]:
c = []
for i in b:
  c.append(i**2)
print(c)
  


[1, 4, 9, 16, 36, 49]


In [ ]:
c.append (z)
print(c)

[20, 40, 50, 60, [8000, 64000, 125000, 216000], [8000, 64000, 125000, 216000]]


In [ ]:
my_word = "Hello World"
print(my_word)

Hello World


In [ ]:
a = []
type(a)

list

In [ ]:
selfa= [1,2,3]

In [ ]:
round(4.556)

5

In [ ]:
a = []

In [ ]:
a,b = (1,2)
type(a)

int

In [ ]:
b= 1,2,3
type(b)

tuple

In [ ]:
a = (1,2,3,[1,2,3],5)
a[3][0]=9
a


(1, 2, 3, [9, 2, 3], 5)

In [ ]:
a = [1,2,3,1,2,3,5]
a[3]=9
a

[1, 2, 3, 9, 2, 3, 5]

In [ ]:
a

[1, 2, 3, 9, 2, 3, 5]

In [ ]:
a.append(10)
a

[1, 2, 3, 9, 2, 3, 5, 10, 10]

In [ ]:
a

[1, 2, 3, 9, 2, 3, 5, 10, 10]

In [ ]:
a.pop(8)


IndexError: ignored

In [ ]:
a

[1, 2, 3, 9, 2, 3, 5, 10]

In [ ]:
helloword = 'hello' +' ' 'word'
print(helloword)

hello word


In [ ]:
lotsofhello = 'hello '*10
print(lotsofhello)

hello hello hello hello hello hello hello hello hello hello 


In [ ]:
a = [1,2,3,4]
b = [5,6,7,8]
c= a + b
print(c)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
g = ['x']
h = ['y']


In [ ]:
k = object
type(k)

type

In [ ]:
x_list = [1]*5
print("x_list contains %o  objects " % len(x_list))


x_list contains 5  objects 


In [ ]:
a = 5%5
a

0

In [ ]:
m = 'shubham %a dandnaik'
m

'shubham %a dandnaik'

In [ ]:
s = 'shubham'
f =   f'my name is {s} {5} '
print(f)

my name is shubham 5 


In [ ]:
a = 10
b = 5
c = a%b
c

0

In [ ]:
name = 'shubham dandnaik '
s = print('name is', name)
s

name is shubham dandnaik 


In [ ]:
clas = 'supriya'
s = f"who is {clas}"
s

'who is supriya'

In [ ]:
print('who is', clas)

who is supriya


In [ ]:
d = {'name' : 'shubham' , 'roll x' : 14}
print (d ['roll x'])

14


In [ ]:
g = [1,2,3,4,5]
print (g[0 : 3])

[1, 2, 3]


In [ ]:
a = range (1,15)
print(list(a))
print (list(a[-1 : -7 : -1]))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[14, 13, 12, 11, 10, 9]


In [ ]:
astring = "Hello world!"
afewwords = astring.split(" ")
print(afewwords)

['Hello', 'world!']


In [ ]:
astring = "Hello world!"
print(astring.startswith("Helo"))
print(astring.endswith("asdfasdfasdf"))

False
False


In [ ]:
m = [1,2,3]
for  i in m :
  print(i)


1
2
3


In [ ]:
name = ['shubham', 'rushabh', 'abhishek']
for i in name :
  print ('name', i)

name shubham
name rushabh
name abhishek


In [ ]:
name = ['shubham', 'rushabh', 'abhishek']
for i in name :
  print(f"name {i}")

name shubham
name rushabh
name abhishek


In [ ]:
a = [1,2,3,4,5]
b = []
for i in a :
  c = b.append(i**2)
  print (c)


None
None
None
None
None


In [ ]:
print(len(a))
print (a.count(2))
c = b.append(a*2)
print (b)

5
1
[1, 4, 9, 16, 25, [1, 2, 3, 4, 5, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]]


In [ ]:
j = 'shubham dandnaik'
c = j.upper
print (j)

shubham dandnaik


In [ ]:
x = 0
while x < 5 :
  print ('good')
  x+= 1 

good
good
good
good
good


In [ ]:
import numpy as np

In [ ]:
array1 = np.array([2,4,6,8])
print(array1)

[2 4 6 8]


In [ ]:
array2 = np.array([1,4,5,6])
print(array2)

[1 4 5 6]


In [ ]:
array3 = np.array([4,5,6,8,7,9])
print(array3)

[4 5 6 8 7 9]


In [ ]:
array4 = np.array((4,5,6))
print(array4)
type(array4)

[4 5 6]


numpy.ndarray

In [ ]:
array5 = np.array({1,2,3})
print(array5)
type(array5)

{1, 2, 3}


numpy.ndarray

In [ ]:
array6 = np.array({'shubham':1 , 'rushabh':2 })
print(array6)
type(array6)

{'shubham': 1, 'rushabh': 2}


numpy.ndarray

In [ ]:
# 2 dimensional array
twodarray = np.array([{'shuhham':2 , 'rushabh':3},{'rushabh':5 , 'shubham':5}])
print(twodarray)
type(twodarray)

[{'shuhham': 2, 'rushabh': 3} {'rushabh': 5, 'shubham': 5}]


numpy.ndarray

In [ ]:
# 3 dimensional array
threedarray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threedarray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
anotherarray = np.array([[1,2,3,4],[5,6,7,8]])
print(anotherarray)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#two dimensional array
morearray = np.array([[1],[2]])
print(morearray)

[[1]
 [2]]


In [ ]:
#3 dimensional array 
arr = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(arr)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [ ]:
# 3 dimensional array
second = np.array([[[1],[2]],[[3],[4]]])
print(second)

[[[1]
  [2]]

 [[3]
  [4]]]


In [ ]:
print(second.shape)
second.ndim

(2, 2, 1)


3

In [ ]:
# another 3d array
another = np.array([[[1,2,3],[4,5,6],[7,8,9],[1,2,3]],[[7,8,9],[1,2,3],[4,5,6],[7,8,9]]])
print(another)
print(another.shape)
print(another.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 2 3]]

 [[7 8 9]
  [1 2 3]
  [4 5 6]
  [7 8 9]]]
(2, 4, 3)
3


In [ ]:
# pandas 

In [ ]:
import pandas as pd

In [ ]:
pandas_series = pd.Series([2,5,4,6],
                          [5,6,7,8])
print(pandas_series)

5    2
6    5
7    4
8    6
dtype: int64


In [ ]:
#to change the index name
panda_series = pd.Series([1,5,6,7,8], index= ['a','b','c','d','e'])
print(panda_series)

a    1
b    5
c    6
d    7
e    8
dtype: int64


In [ ]:
print(panda_series[0])

panda_series['a']

1


1

In [ ]:
# random integer with 5 rows and 4 columns
some2d_array = np.random.randint(10,20,(5,4))
panda_frame = pd.DataFrame(some2d_array , columns = ['one', 'two', 'three','four'])
panda_frame

one  two  three  four
0   11   14     12    17
1   10   16     19    18
2   19   13     13    14
3   19   18     19    11
4   19   17     11    18

In [ ]:
# random integer with 5 rows and 4 columns changed name of rows and columns
some2d_array = np.random.randint(10,20,(5,4))
print(some2d_array)
panda_frame = pd.DataFrame(some2d_array , columns = ['one', 'two', 'three','four'], index=['a','b','c','d','e'])
panda_frame

[[10 10 12 13]
 [13 18 13 11]
 [14 10 10 11]
 [10 10 19 16]
 [19 10 19 19]]


one  two  three  four
a   10   10     12    13
b   13   18     13    11
c   14   10     10    11
d   10   10     19    16
e   19   10     19    19

In [ ]:
# list of list
listoflist = [['shubham',10],['rushabhm',12]]
pd.DataFrame(listoflist)

0   1
0   shubham  10
1  rushabhm  12

In [ ]:
#pandas on ditctionary keys will be the name of column and the values will be arrange in rows
dictionary = {'students': [12,13,14], 'marks':[10,12,13]}
pd.DataFrame(dictionary)


students  marks
0        12     10
1        13     12
2        14     13

In [ ]:
#for list of dictionaries
list_of_dict =[{'a':1,'b':2,'c':3},{'a':4,'b':5,'c':6 }]
pd.DataFrame(list_of_dict)

a  b  c
0  1  2  3
1  4  5  6

In [ ]:
#for list of dictionaries  with unequal arg or when thw keys are different in dict
list_of_dict =[{'a':1,'b':2,'c':3},{'a':4,'b':5,'c':6 , 'd': 8}]
pd.DataFrame(list_of_dict)

a  b  c    d
0  1  2  3  NaN
1  4  5  6  8.0

In [ ]:
#list of list in dataframe
list_of_list = [['shubham','rushabh','abhishek'],[1,2,3],[4,5,6]]
print(np.array(list_of_list))
pd.DataFrame(list_of_list,index = ['a','b','c'])

[['shubham' 'rushabh' 'abhishek']
 ['1' '2' '3']
 ['4' '5' '6']]


0        1         2
a  shubham  rushabh  abhishek
b        1        2         3
c        4        5         6

In [ ]:
a = {'shubham': 1 , 'rushabh':2}
b = {'abhiskek' : 4 , 'mohit':5}
list(zip(a,b))

[('shubham', 'abhiskek'), ('rushabh', 'mohit')]

In [ ]:
list_of_name = ['shubham','abhishek','rushabh']
list_of_age = [22,23,np.nan]
list_of_tuples = list(zip(list_of_name,list_of_age))
print(list_of_tuples)
dataframe = pd.DataFrame(list_of_tuples, columns = ['name','age'])
dataframe



[('shubham', 22), ('abhishek', 23), ('rushabh', nan)]


name   age
0   shubham  22.0
1  abhishek  23.0
2   rushabh   NaN

In [ ]:
x = 2
for i in range (x):
  x-=2
  print(x)


0
-2


In [ ]:
x = 'abcd'
for i in x:
  print(i)
  

a
b
c
d


In [ ]:
x.upper()

'ABCD'

In [ ]:
i = 0
while i<3:
  i+=1
  print(i)
else:
  print(0)

1
2
3
0


In [ ]:
i = 1
while False:
   if i%2==0:
     break
     print(i)

   


In [ ]:
i =0
while i<3:
  i+=1
  print(i)
else:
  print(0)

1
2
3
0


In [ ]:
# DATA WRANGLING


In [ ]:
import numpy as np
import pandas as pd


In [ ]:
file_path = '/content/Copy of imdb_data.csv'
imdb_df=pd.read_csv(file_path)

In [ ]:
imdb_df.head().T

0  \
id                                                                     1   
belongs_to_collection  [{'id': 313576, 'name': 'Hot Tub Time Machine ...   
budget                                                          14000000   
genres                                    [{'id': 35, 'name': 'Comedy'}]   
homepage                                                             NaN   
imdb_id                                                        tt2637294   
original_language                                                     en   
original_title                                    Hot Tub Time Machine 2   
overview               When Lou, who has become the "father of the In...   
popularity                                                      6.575393   
poster_path                             /tQtWuwvMf0hCc2QR2tkolwl7c3c.jpg   
production_companies   [{'name': 'Paramount Pictures', 'id': 4}, {'na...   
production_countries   [{'iso_3166_1': 'US', 'name': 'United States o...   
release_date                                                     2/20/15   
runtime                                                             93.0   
spoken_languages                [{'iso_639_1': 'en', 'name': 'English'}]   
status                                                          Released   
tagline                The Laws of Space and Time are About to be Vio...   
title                                             Hot Tub Time Machine 2   
Keywords               [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
cast                   [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
crew                   [{'credit_id': '59ac067c92514107af02c8c8', 'de...   
revenue                                                         12314651   

                                                                       1  \
id                                                                     2   
belongs_to_collection  [{'id': 107674, 'name': 'The Princess Diaries ...   
budget                                                          40000000   
genres                 [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
homepage                                                             NaN   
imdb_id                                                        tt0368933   
original_language                                                     en   
original_title                  The Princess Diaries 2: Royal Engagement   
overview               Mia Thermopolis is now a college graduate and ...   
popularity                                                      8.248895   
poster_path                             /w9Z7A0GHEhIp7etpj0vyKOeU1Wx.jpg   
production_companies         [{'name': 'Walt Disney Pictures', 'id': 2}]   
production_countries   [{'iso_3166_1': 'US', 'name': 'United States o...   
release_date                                                      8/6/04   
runtime                                                            113.0   
spoken_languages                [{'iso_639_1': 'en', 'name': 'English'}]   
status                                                          Released   
tagline                It can take a lifetime to find true love; she'...   
title                           The Princess Diaries 2: Royal Engagement   
Keywords               [{'id': 2505, 'name': 'coronation'}, {'id': 42...   
cast                   [{'cast_id': 1, 'character': 'Mia Thermopolis'...   
crew                   [{'credit_id': '52fe43fe9251416c7502563d', 'de...   
revenue                                                         95149435   

                                                                       2  \
id                                                                     3   
belongs_to_collection                                                NaN   
budget                                                           3300000   
genres                                     [{'id': 18, 'name': 'Drama'}]   
homepage                               ht

In [ ]:
imdb_df.shape

(3000, 23)

In [ ]:
imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     3000 non-null   int64  
 1   belongs_to_collection  604 non-null    object 
 2   budget                 3000 non-null   int64  
 3   genres                 2993 non-null   object 
 4   homepage               946 non-null    object 
 5   imdb_id                3000 non-null   object 
 6   original_language      3000 non-null   object 
 7   original_title         3000 non-null   object 
 8   overview               2992 non-null   object 
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object 
 11  production_companies   2844 non-null   object 
 12  production_countries   2945 non-null   object 
 13  release_date           3000 non-null   object 
 14  runtime                2998 non-null   float64
 15  spok

# data wrangling

In [ ]:
#to drop the column as it does not contain any information
imdb_df.drop('id', axis=1 , inplace=True)


In [ ]:
#when we use only describe it gives us the description of only numeric values 
imdb_df.describe()

id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [ ]:
#when we use only describe it gives us the description of only numeric values 
imdb_df.describe(include = 'all')

belongs_to_collection        budget  \
count                                                 604  3.000000e+03   
unique                                                422           NaN   
top     [{'id': 645, 'name': 'James Bond Collection', ...           NaN   
freq                                                   16           NaN   
mean                                                  NaN  2.253133e+07   
std                                                   NaN  3.702609e+07   
min                                                   NaN  0.000000e+00   
25%                                                   NaN  0.000000e+00   
50%                                                   NaN  8.000000e+06   
75%                                                   NaN  2.900000e+07   
max                                                   NaN  3.800000e+08   

                               genres                           homepage  \
count                            2993                                946   
unique                            872                                941   
top     [{'id': 18, 'name': 'Drama'}]  http://www.transformersmovie.com/   
freq                              266                                  4   
mean                              NaN                                NaN   
std                               NaN                                NaN   
min                               NaN                                NaN   
25%                               NaN                                NaN   
50%                               NaN                                NaN   
75%                               NaN                                NaN   
max                               NaN                                NaN   

          imdb_id original_language original_title  \
count        3000              3000           3000   
unique       3000                36           2975   
top     tt2637294                en         Joshua   
freq            1              2575              2   
mean          NaN               NaN            NaN   
std           NaN               NaN            NaN   
min           NaN               NaN            NaN   
25%           NaN               NaN            NaN   
50%           NaN               NaN            NaN   
75%           NaN               NaN            NaN   
max           NaN               NaN            NaN   

                                                 overview   popularity  \
count                                                2992  3000.000000   
unique                                               2992          NaN   
top     When Lou, who has become the "father of the In...          NaN   
freq                                                    1          NaN   
mean                                                  NaN     8.463274   
std                                                   NaN    12.104000   
min                                                   NaN     0.000001   
25%                                                   NaN     4.018053   
50%                                                   NaN     7.374861   
75%                                                   NaN    10.890983   
max                                                   NaN   294.337037   

                             poster_path  ... release_date      runtime  \
count                               2999  ...         3000  2998.000000   
unique                              2999  ...         2398          NaN   
top     /tQtWuwvMf0hCc2QR2tkolwl7c3c.jpg  ...      9/10/10          NaN   
freq                                   1  ...            5          NaN   
mean                                 NaN  ...          NaN   107.856571   
std                                  NaN  ...          NaN    22.086434   
min                                  NaN  ...          NaN     0.000000   
25%                                  NaN  ...          NaN    94.000000   
50%      

In [ ]:
# Create three dataframes

# Runtime >= 150 mins
imdb1 = imdb_df[imdb_df['runtime'] >= 150].reset_index(drop=True)

imdb2 = imdb_df[ (imdb_df['runtime'] < 150) & (imdb_df['runtime'] > 100 )].reset_index(drop=True)

imdb3 = imdb_df[imdb_df['runtime'] <= 100].reset_index(drop=True)

In [ ]:
imdb1.shape

(135, 22)

In [ ]:
imdb2.shape

(1586, 22)

In [ ]:
imdb3.shape

(1277, 22)

In [ ]:
imdb1


belongs_to_collection    budget  \
0                     NaN  44000000   
1                     NaN  12000000   
2                     NaN    500000   
3                     NaN         0   
4                     NaN  72000000   
..                    ...       ...   
130                   NaN  22000000   
131                   NaN  18000000   
132                   NaN  12000000   
133                   NaN  31500000   
134                   NaN  61000000   

                                                genres  \
0    [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...   
1    [{'id': 12, 'name': 'Adventure'}, {'id': 35, '...   
2    [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...   
3    [{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...   
4    [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...   
..                                                 ...   
130  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...   
131  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...   
132  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
133  [{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...   
134  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   

                             homepage    imdb_id original_language  \
0         http://thehatefuleight.com/  tt3460252                en   
1                                 NaN  tt0059243                en   
2                                 NaN  tt0242572                ta   
3                                 NaN  tt1772980                ru   
4                                 NaN  tt0112573                en   
..                                ...        ...               ...   
130                               NaN  tt0083987                en   
131                               NaN  tt0086879                en   
132                               NaN  tt0060934                en   
133      http://www.apocalypsenow.com  tt0078788                en   
134  http://www.lesmiserablesfilm.com  tt1707386                en   

                original_title  \
0            The Hateful Eight   
1               The Great Race   
2    Kandukondain Kandukondain   
3                       Mishen   
4                   Braveheart   
..                         ...   
130                     Gandhi   
131                    Amadeus   
132           The Sand Pebbles   
133             Apocalypse Now   
134             Les Misérables   

                                              overview  popularity  \
0    Bounty hunters seek shelter from a raging bliz...   20.328822   
1    Professional daredevil and white-suited hero, ...    4.473327   
2    Two young women with differing views on love f...    0.660663   
3    In the year 2020, a group of wealthy Moscovite...    1.042112   
4    Enraged at the slaughter of Murron, his new br...   20.755149   
..                                                 ...         ...   
130  In the early years of the 20th century, Mohand...   12.383755   
131  The incredible story of genius musician Wolfga...   12.677592   
132  Engineer Jake Holman arrives aboard the gunboa...   11.354247   
133  At the height of the Vietnam war, Captain Benj...   13.596300   
134  An adaptation of the successful stage musical ...   13.524080   

                          poster_path  ... release_date runtime  \
0    /fqe8JxDNO8B8QfOGTdjh6sPCdSC.jpg  ...     12/25/15   167.0   
1    /nc6FRAVC4a8o4podiFy2P5qI9ul.jpg  ...       7/1/65   160.0   
2    /AnhaX3iivU7aLc6fLuAuHXTsbgO.jpg  ...       5/5/00   157.0   
3    /uMzkG73Y5qL9tiRrXnGlndOqhbJ.jpg  ...      6/26/11   158.0   
4    /2qAgGeYdLjelOEqjW9FYvPHpplC.jpg  ...      5/24/95   177.0   
..                                ...  ...          ...     ...   
130  /2z9A4FSu1YySrhhcuqkdMIXpgyN.jpg  ...     11/30/82   191.0   
131  /flnoqdC38mbaulAeptjynOFO7yi.jpg  ...     10/26/84   160.0   
132  /zgahpKXixtsmveyl9oPOD7GhmpW.jpg  ...     12/20/66   182.0   
133  /jcvJ2xcVWU9Wh0hZAxcs103s8nN.jpg  ...      8/15/79   153.0   
134  /qEsr

In [ ]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]

In [ ]:
d = a+b+c
d

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#to concate the list in pandas
list_df = [imdb1,imdb2,imdb3]
non_null_values = pd.concat(list_df , axis=1 )
non_null_values.shape

(1586, 66)

In [ ]:
#another method of concat
non_null_no = pd.concat([imdb1 , imdb2 , imdb3 ], axis=1)
non_null_no.shape

(1586, 66)